# Generated by Django 3.2.2 on 2021-06-10 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_name', models.CharField(max_length=100)),
                ('leave_rule', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_per_year', models.CharField(blank=True, max_length=100, null=True)),
                ('leave_carried_forward', models.CharField(blank=True, max_length=100, null=True)),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('typeleave', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
