# Generated by Django 3.2.2 on 2021-06-10 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0001_leave_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_week_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(blank=True, max_length=100, null=True)),
                ('working_off', models.CharField(blank=True, default=0, max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
