# Generated by Django 3.2.2 on 2021-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_leave_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='application_date',
            field=models.DateField(blank=True),
        ),
    ]
