# Generated by Django 3.2.2 on 2021-06-24 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_management', '0006_reject_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_policy', models.CharField(blank=True, max_length=2000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_leave_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
