# Generated by Django 3.2.2 on 2021-06-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
